version: '3.8'

services:
  neo4j:
    image: neo4j
    container_name: neo4j-container
    ports:
      - "7474:7474"  
      - "7687:7687"  
    environment:
      NEO4J_AUTH: neo4j/aveQho9yf6tx29vgW3kv
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data:
